[package]
description = "The fast, collaborative code editor."
edition.workspace = true
name = "zedtui"
version = "0.1.0"
publish.workspace = true
license = "GPL-3.0-or-later"
authors = ["Zed Team <hi@zed.dev>"]

[lints]
workspace = true

[[bin]]
name = "zedtui"
path = "src/main.rs"

[lib]
name = "zedtui"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
backtrace = "0.3"
clap.workspace = true
env_logger.workspace = true
serde.workspace = true
rayon.workspace = true

fs.workspace = true
log.workspace = true
gpui.workspace = true
paths.workspace = true
release_channel.workspace = true
settings.workspace = true
system_specs.workspace = true
tui.workspace = true
util.workspace = true
zlog.workspace = true

[dev-dependencies]
